name: photos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^0.5.8
  photo_view: ^0.10.3
  cupertino_icons: ^1.0.0
  fl_chart: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
  uses-material-design: true
